[package]
name = "cronparse"
description = "Crontab files parser"
version = "0.1.1"
authors = ["Konstantin Stepanov <me@kstep.me>"]
readme = "README.md"
repository = "https://github.com/kstep/cronparse.rs.git"
license = "MIT"
keywords = ["cron", "crontab", "parser"]
